name: "BoomchainLabs Attest Build Provenance"
description: "Generate signed build provenance attestations for Docker images and workflow artifacts"
author: "BoomchainLabs"
branding:
  color: "blue"
  icon: "lock"

inputs:
  subject-path:
    description: "Path(s) to artifact(s). Only one of subject-path, subject-digest, or subject-checksums can be used."
    required: false
  subject-digest:
    description: "Digest of the subject (algorithm:hex_digest). Requires subject-name."
    required: false
  subject-name:
    description: "Name of the subject. Required when using subject-digest."
    required: false
  subject-checksums:
    description: "Path to a file containing digests and names of artifacts."
    required: false
  predicate-type:
    description: "URI identifying the type of the attestation predicate."
    required: true
  predicate:
    description: "JSON string containing the attestation predicate. Max 16MB."
    required: true
  predicate-path:
    description: "Path to file containing predicate. Max 16MB. Only one of predicate/predicate-path can be used."
    required: false
  push-to-registry:
    description: "Push attestation to registry (requires subject-name & subject-digest)."
    default: false
  create-storage-record:
    description: "Create GitHub storage record (requires push-to-registry=true)."
    default: true
  show-summary:
    description: "Attach list of generated attestations to workflow summary."
    default: true
  github-token:
    description: "GitHub token for authenticated API requests."
    default: ${{ github.token }}

outputs:
  bundle-path:
    description: "Path to the attestation bundle."
  attestation-id:
    description: "Attestation ID."
  attestation-url:
    description: "URL for the attestation summary."
  storage-record-ids:
    description: "GitHub IDs of created storage records."

runs:
  using: "composite"
  steps:
    - name: Attest
      id: attest
      uses: actions/attest@v4.0.0
      with:
        subject-path: ${{ inputs.subject-path }}
        subject-digest: ${{ inputs.subject-digest }}
        subject-name: ${{ inputs.subject-name }}
        subject-checksums: ${{ inputs.subject-checksums }}
        predicate-type: ${{ inputs.predicate-type }}
        predicate: ${{ inputs.predicate }}
        predicate-path: ${{ inputs.predicate-path }}
        push-to-registry: ${{ inputs.push-to-registry }}
        create-storage-record: ${{ inputs.create-storage-record }}
        show-summary: ${{ inputs.show-summary }}
        github-token: ${{ inputs.github-token }}
